const profile = [
    {
      id: "62bbcfce7ea16b00aad69049",
      index: 0,
      guid: "744b445a-2452-4015-ac25-b7a1e8152f7f",
      isActive: true,
      balance: "$2,976.50",
      picture: "http://placehold.it/32x32",
      age: 34,
      eyeColor: "green",
      name: "Beach Saunders",
      gender: "male",
      company: "ACCUFARM",
      email: "beachsaunders@accufarm.com",
      phone: "+1 (944) 433-2781",
      address: "756 Kansas Place, Kylertown, Connecticut, 1539",
      about: "Ea culpa dolore deserunt in anim non ut ullamco occaecat. Et ipsum sint enim mollit voluptate cupidatat sunt duis sit amet cillum exercitation non nulla. Fugiat amet ad exercitation pariatur incididunt exercitation et quis aute et ipsum ex excepteur. Qui nulla aliqua officia laboris qui fugiat sit ut elit. Velit aute cillum officia commodo mollit cillum qui velit consequat veniam. Veniam dolore nisi occaecat minim consequat laboris. Proident anim sint aliquip laborum reprehenderit ex.\r\n"
    },
    {
      id: "62bbcfce542ef97ae18ef311",
      index: 1,
      guid: "a5ee4547-92cb-4bd9-902d-2da2ecab0d28",
      isActive: true,
      balance: "$2,813.31",
      picture: "http://placehold.it/32x32",
      age: 22,
      eyeColor: "green",
      name: "Casandra Murray",
      gender: "female",
      company: "SKYPLEX",
      email: "casandramurray@skyplex.com",
      phone: "+1 (873) 566-3460",
      address: "454 Carlton Avenue, Clayville, Northern Mariana Islands, 9908",
      about: "Non labore elit id mollit ea labore incididunt esse. Anim non culpa veniam aliqua. Magna veniam consequat esse veniam elit exercitation ullamco ad. Id qui pariatur mollit minim nostrud consectetur Lorem tempor do commodo. Ex voluptate elit enim aute proident officia pariatur consequat cillum reprehenderit nisi qui consequat cupidatat. Voluptate laboris elit enim veniam veniam. Laborum deserunt officia aliquip amet laboris nostrud amet commodo ullamco velit non do consectetur reprehenderit.\r\n"
    },
    {
      id: "62bbcfce431f863a3ffe99d3",
      index: 2,
      guid: "fd6a0e74-5eaf-48ab-9f6e-4acdb9bb8048",
      isActive: false,
      balance: "$2,985.94",
      picture: "http://placehold.it/32x32",
      age: 33,
      eyeColor: "brown",
      name: "Rachel Avila",
      gender: "female",
      company: "PLASMOSIS",
      email: "rachelavila@plasmosis.com",
      phone: "+1 (826) 471-2583",
      address: "307 Kay Court, Hatteras, Illinois, 5468",
      about: "Non duis eiusmod tempor aliquip do duis. Incididunt irure deserunt non nisi enim excepteur consequat proident adipisicing mollit ullamco consequat minim duis. Aliquip elit qui et velit ipsum veniam nulla dolore dolore irure deserunt. Nisi non laboris aliqua tempor dolore elit nisi eiusmod cillum mollit qui nisi ad. Cillum veniam et elit esse magna sit incididunt. Incididunt Lorem consequat irure laborum aliquip ipsum.\r\n"
    },
    {
      id: "62bbcfced57a921179e32071",
      index: 3,
      guid: "1c6a2382-dea6-4bff-a727-8daf474e4192",
      isActive: true,
      balance: "$1,286.00",
      picture: "http://placehold.it/32x32",
      age: 21,
      eyeColor: "green",
      name: "Marlene Bray",
      gender: "female",
      company: "ZIALACTIC",
      email: "marlenebray@zialactic.com",
      phone: "+1 (902) 527-3823",
      address: "604 Kaufman Place, Elbert, Marshall Islands, 4390",
      about: "Pariatur amet culpa non veniam incididunt enim irure non labore nisi. Id consequat et amet sit sint eiusmod. Nisi quis ut occaecat sit labore enim aute officia. Reprehenderit quis minim labore ad. Sunt veniam dolore pariatur ullamco anim ea. Consectetur voluptate deserunt nostrud aliqua minim incididunt laborum incididunt aliqua anim laboris ipsum magna sit. Veniam nulla fugiat adipisicing eiusmod.\r\n"
    },
    {
      id: "62bbcfcecc05982efe35b1d6",
      index: 4,
      guid: "da6c81f9-f701-4d0b-b686-1f221f9f84f6",
      isActive: true,
      balance: "$3,971.37",
      picture: "http://placehold.it/32x32",
      age: 22,
      eyeColor: "blue",
      name: "Cheryl Waller",
      gender: "female",
      company: "EQUITOX",
      email: "cherylwaller@equitox.com",
      phone: "+1 (843) 401-3746",
      address: "685 Maple Street, Wescosville, Indiana, 4704",
      about: "Cupidatat fugiat labore ad deserunt laborum consectetur elit sunt incididunt. Deserunt aliqua cupidatat nisi labore tempor eu dolore. Non labore voluptate nulla ut sint velit amet deserunt eiusmod elit.\r\n"
    }
  ];

  module.exports = {profile}